### ISSUE TITLE
Add a way to ignore a certain file for routes this can be empty array as well

### ISSUE THREAD

**Issue by isheraz** [waqar-invozone/budget#3]
https://github.com/waqar-invozone/budget/blob/54f13c845e6b3128123a8087c3f9ca0c9187a14c/routes/index.js#L10

**Comment by waqar-invozone** [comment]
https://github.com/waqar-invozone/budget/blob/868663422df2debe0b54d7ac12f13194252e20e9/routes/index.js#L13
